<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
	  <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.18" />
    <PackageReference Include="Volo.Abp.AspNetCore" Version="10.6.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Iptv.EntityFrameworkCore\Iptv.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\Iptv.HttpApi\Iptv.HttpApi.csproj" />
  </ItemGroup>

</Project>
