<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Iptv.Application.Contracts\Iptv.Application.Contracts.csproj" />
    <ProjectReference Include="..\Iptv.Application\Iptv.Application.csproj" />
  </ItemGroup>

</Project>
